name: Pre-release

on:
  push:
    branches:
      - next

permissions:
  contents: read
  # note: no write permissions are needed since the workflow uses GH_ACCESS_TOKEN instead of GITHUB_TOKEN

jobs:
  prerelease:
    if: ${{ github.repository_owner == 'better-auth' }}
    name: Create a pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v4

      - run: pnpm install
      
      - name: Build
        run: pnpm build

      - name: Enter pre-release mode (if not already)
        run: npx changeset pre enter next

      - name: Create Version PR or Publish Pre-release
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(pre-release): version packages"
          title: "chore(pre-release): version packages"
          version: node .github/prerelease.js
          publish: npx changeset publish --tag next
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_ENV: "production"